include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    unused_import: ignore
    deprecated_member_use: ignore
    non_constant_identifier_names: ignore
    curly_braces_in_flow_control_structures: ignore
    use_super_parameters: ignore
    use_build_context_synchronously: ignore
    file_names: ignore
    avoid_print: ignore
    prefer_function_declarations_over_variables: ignore
