name: healsearch_app
description: A healthcare search application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  google_nav_bar: ^5.0.6
  http: ^1.2.2
  connectivity_plus: ^5.0.2  # For network connectivity checks

  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  toggle_switch: ^2.0.1
  cupertino_icons: ^1.0.2
  
  # Mobile-specific UI packages
  flutter_native_splash: ^2.2.14
  google_fonts: ^6.2.1
  
  # Firebase packages
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  
  # Form validation
  form_field_validator: ^1.1.0
  flutter_pw_validator: ^1.5.0
  email_validator: ^3.0.0
  
  # UI components
  quickalert: ^1.0.1
  group_button: ^5.2.2
  animated_floating_buttons: ^0.0.2
  flutter_awesome_buttons: ^1.1.0
  flutter_switch: ^0.3.2
  
  # Mobile services
  email_otp: ^3.0.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  flutter_map: ^7.0.2
  url_launcher: ^6.1.10
  path_provider: ^2.0.14
  image_picker: ^1.1.2
  
  # Miscellaneous utilities
  encrypt: ^5.0.1
  uuid: ^4.3.3
  dash_chat_2: ^0.0.21
  
  # AI features
  google_sign_in: ^5.0.7
  flutter_gemini: ^3.0.0
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/logo1.png
    - images/logo.png
    - images/logo3.png
    - images/logo4.png
    - images/man.png
    - images/plants2.png
    - images/bkg.jpg
    - images/favorite.png
    - images/search.png
    - images/back.png
    - images/products.png
    - images/user.png
    - images/box.png
